### ISSUE TITLE
Production build requires react-hot-loader

### ISSUE THREAD

**Issue by w01fgang** [ItsMrAkhil/react-styled-carousel#22]
Fails in production:
```
{ Error: Cannot find module 'react-hot-loader'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /user_code/node_modules/react-styled-carousel/build/components/SliderTrack.js:16:48
    at Object.<anonymous> (/user_code/node_modules/react-styled-carousel/build/components/SliderTrack.js:19:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12) code: 'MODULE_NOT_FOUND' }
```

node_modules/react-styled-carousel/build/components/SliderTrack.js
```javascript
(function () {
  var enterModule = require('react-hot-loader').enterModule;

  enterModule && enterModule(module);
})();
```

Version: 0.4.11

**Comment by ItsMrAkhil** [comment]
@w01fgang This is an issue with the react-hot-loader. They are including it even I'm not using it anywhere in the build files. But fortunately, they have a fix that has to use NODE_ENV=production while building.

I've fixed this and pushed it to version: 0.4.12

Feel free to open the issue again if you didn't get this resolved.
