### ISSUE TITLE
Issue with server side rendering

### ISSUE THREAD

**Issue by cloutiertyler** [ItsMrAkhil/react-styled-carousel#31]
When I try to render
```
        <Slider>
          <div>Hey</div>
          <div>Hey</div>
          <div>Hey</div>
          <div>Hey</div>
        </Slider>
```
on the server I get the following error.

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
at invariant (/usr/src/app/node_modules/fbjs/lib/invariant.js:42:15)
at ReactDOMServerRenderer.render (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2522:7)
at ReactDOMServerRenderer.read (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2354:19)
 at Object.renderToString (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2726:25)
at Object.default_1 [as default] (/usr/src/app/src/lib/render.ts:15:16)
at Object.<anonymous> (/usr/src/app/src/routes/client.tsx:25:18)
at step (/usr/src/app/src/routes/client.tsx:32:23)
at Object.next (/usr/src/app/src/routes/client.tsx:13:53)
at /usr/src/app/src/routes/client.tsx:7:71
at new Promise (<anonymous>) name: 'Invariant Violation', framesToPop: 1 }
```

This is my render code:
```
  const sheet = new ServerStyleSheet(); // <-- creating out stylesheet
  const body = renderToString(sheet.collectStyles(element));
```

Am I missing something to be able to render server side? Sweet library by the way!

**Comment by cloutiertyler** [comment]
I figured it out. It was a problem with the way I was importing using `require`.

I needed to do
```
const Slider = require("react-styled-carousel").default;
```
